name: Cloud
description: Create a Cloud issue.
title: "[Cloud] Title"
labels: "area/cloud"
body:
- type: textarea
  id: cloud
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description of the issue you want to report with Yugabyte Cloud.**
      
      **Include the steps to reproduce the issue.**
  validations:
    required: true
