name: Core-DocDB
description: Choose this template to create a DocDB issue.
title: "[docDB] Title"
labels: "area/docdb"
body:
- type: textarea
  id: docDB
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description of the issue you want to report with the DocDB document store.**
      **Include the steps to reproduce the issue.**
  validations:
    required: true 
