name: Core-YCQL
description: Choose this template to create a YCQL issue.
title: "[YCQL] Title"
labels: "area/ycql"
body:
- type: textarea
  id: ycql
  attributes:
    label: Description
    placeholder: |
      **Provide a detailed description of the issue you want to report related to YCQL.**
      **Include relevant steps to reproduce the issue.**
  validations:
    required: true 
